myproject/college_asset/urls.py
from django.urls import path
from . import views

app_name = 'college_asset'

urlpatterns = [
    path('register_asset/', views.register_asset, name='register_asset'),
    path('add_classroom/', views.add_classroom, name='add_classroom'),
    path('assign_asset/', views.assign_asset, name='assign_asset'),
    path('classroom_list/', views.classroom_list, name='classroom_list'),
    path('edit_asset/<int:asset_id>/', views.edit_asset, name='edit_asset'),
    path('edit_classroom/<int:classroom_id>/', views.edit_classroom, name='edit_classroom'),
    path('edit_classroom_asset/<int:classroom_asset_id>/', views.edit_classroom_asset, name='edit_classroom_asset'),
    path('delete_asset/<int:asset_id>/', views.delete_asset, name='delete_asset'),
    path('delete_classroom/<int:classroom_id>/', views.delete_classroom, name='delete_classroom'),
    path('delete_classroom_asset/<int:classroom_asset_id>/', views.delete_classroom_asset, name='delete_classroom_asset'),
    path('classroom_report/', views.classroom_report, name='classroom_report'),
    path('asset_pie_chart/', views.asset_pie_chart, name='asset_pie_chart'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls')),
    path('college_asset/',include('college_asset.urls')),
    path('users/', include('users.urls')),
    
    
]

myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.posts_list,name= "list"),
    path('<slug:slug>',views.post_page,name= "page"),

]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_view, name = "register"),
    path('login/',views.login_view, name = "login"),
    path('logout/',views.logout_view, name = "logout"),

]

myproject/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check Out my <a href="/about">About</a>page.</p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Django App {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">
        <span role="img" aria-label="Home">🏠</span>
      </a>
      |
      <a href="/about">
        <span role="img" aria-label="About">😀</span>
      </a>
      |
      <a href="{% url 'posts:list' %}">
        <span role="img" aria-label="Posts">📰</span>
      </a> |
  {%if user.is_authenticated %}
      <a href="{% url 'college_asset:classroom_list' %}">
        <span role= "img" aria-label = "Classroom Management" title ="Classroom Management">🏛</span>
      </a>
      <form class="logout" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button
          class="logout-button"
          aria-label="User Logout"
          title="User Logout"
        >
          👋
        </button>
      </form>
  {%else%}
      <a href="{% url 'users:register' %}">
        <span role="img" aria-label="User Registeration">🚀</span>
      </a>
      |
      <a href="{% url 'users:login' %}">
        <span role="img" aria-label="User Login" title=" User Login">🔐</span>
      </a>

  {%endif%}
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>