myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls')),
    path('college_asset/',include('college_asset.urls')),
    path('users/', include('users.urls')),
    
    
]

myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.posts_list,name= "list"),
    path('<slug:slug>',views.post_page,name= "page"),

]

myproject/posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

def __str__(self):
    return self.title

myproject/posts/views.py
from django.shortcuts import render
from . models import Post
from django.http import HttpResponse
# Create your views here.


def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html',{'posts':posts})
def post_page(request,slug):
    return HttpResponse(slug)

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
    <h1>Posts</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{%  url 'posts:page' slug=post.slug %}">
                    {{ post.title }}
                </a>
            </h2>
            <p>{{ post.date }}</p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>
{% endblock %}